# Generated by Django 3.2.13 on 2022-05-01 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('age', models.IntegerField(null=True)),
                ('preferred_location', models.CharField(max_length=300, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50, null=True)),
                ('display_photo', models.ImageField(blank=True, default='default_display_photo.jpg', null=True, upload_to='display_photo')),
                ('banner_photo', models.ImageField(blank=True, default='default_banner_photo.jpg', null=True, upload_to='banner_photo')),
                ('description', models.TextField(max_length=400, null=True)),
                ('education_level', models.CharField(blank=True, choices=[('Secondary', 'Secondary'), ('Post-Secondary', 'Post-Secondary'), ('Univeristy', 'Univeristy'), ('Masters', 'Masters'), ('PhD', 'PhD')], default=None, max_length=20, null=True)),
                ('occupation', models.CharField(max_length=500, null=True)),
                ('beliefs', models.CharField(blank=True, choices=[('Christianity', 'Christianity'), ('Muslim', 'Muslim'), ('Other', 'Other')], default=None, max_length=12, null=True)),
                ('preferred_address', models.CharField(blank=True, max_length=600, null=True)),
                ('full_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
