# Generated by Django 3.2.13 on 2022-05-07 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect_app', '0005_alter_homelistingimages_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houselisting',
            name='photo_upload',
        ),
    ]
