# Generated by Django 3.2.13 on 2022-05-07 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect_app', '0006_remove_houselisting_photo_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='homelistingimages',
            name='house_listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='connect_app.houselisting'),
        ),
    ]
