# Generated by Django 3.2.13 on 2022-05-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_app', '0008_auto_20220507_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homelistingimages',
            name='upload',
            field=models.ImageField(blank=True, default='connect/default_bp.jpg', null=True, upload_to='connect/%Y/%m/%d/'),
        ),
    ]
