# Generated by Django 3.2.13 on 2022-05-05 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20220503_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
