# Generated by Django 3.2.13 on 2022-05-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_member_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='budget',
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(blank=True, choices=[('Lister', 'Lister'), ('Tenant', 'Tenant'), ('Landlord', 'Landlord')], default=None, max_length=50, null=True),
        ),
    ]
