# Generated by Django 3.2.13 on 2022-05-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20220506_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
