# Generated by Django 3.2.13 on 2022-05-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_member_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='education_level',
            field=models.CharField(blank=True, choices=[('Secondary', 'Secondary'), ('Post-Secondary', 'Post-Secondary'), ('Tertiary', 'Tertiary'), ('Masters', 'Masters'), ('PhD', 'PhD')], default=None, max_length=20, null=True),
        ),
    ]
