# Generated by Django 3.2.13 on 2022-05-10 11:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_rename_preferred_address_member_current_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='interests',
        ),
        migrations.AddField(
            model_name='interest',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='member', to=settings.AUTH_USER_MODEL),
        ),
    ]
