# Generated by Django 3.2.13 on 2022-05-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_auto_20220510_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='member',
        ),
        migrations.AddField(
            model_name='member',
            name='interests',
            field=models.ManyToManyField(help_text='Your interests, for matching you to your co-tenant', related_name='interests', to='members.Interest'),
        ),
    ]
