# Generated by Django 3.2.13 on 2022-05-10 14:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_auto_20220510_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='interests',
        ),
        migrations.AddField(
            model_name='interest',
            name='member',
            field=models.ManyToManyField(blank=True, help_text='Your interests, for matching you to your co-tenant', related_name='member', to=settings.AUTH_USER_MODEL),
        ),
    ]
