# Generated by Django 3.2.13 on 2022-05-10 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_auto_20220510_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='member',
        ),
        migrations.AddField(
            model_name='interest',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL),
        ),
    ]
