# Generated by Django 3.2.13 on 2022-05-10 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_auto_20220510_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='interests',
        ),
        migrations.AddField(
            model_name='member',
            name='interests',
            field=models.ForeignKey(help_text='Your interests, for matching you to your co-tenant', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='members.interest'),
        ),
    ]
