# Generated by Django 3.2.13 on 2022-05-10 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_auto_20220510_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='interests',
        ),
    ]
