# Generated by Django 3.2.13 on 2022-05-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_remove_member_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='interests',
            field=models.ManyToManyField(help_text='Your interests, for matching you to your co-tenant', related_name='interests', to='members.Interest'),
        ),
    ]
