# Generated by Django 3.2.13 on 2022-05-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_member_interests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='interests',
        ),
        migrations.AddField(
            model_name='member',
            name='interests',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
