# Generated by Django 3.2.13 on 2022-05-11 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0024_auto_20220511_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='interests',
        ),
    ]
